services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.development
      - path: ./.env
        required: false

  valkey:
    image: valkey/valkey:8-alpine
    restart: always

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.development
      - path: ./.env
        required: false
    depends_on:
      - db
      - valkey

volumes:
  postgres_data:
