# Generated by Django 5.2.6 on 2025-09-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("registered", "Registered"),
                    ("unregistered", "Unregistered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
