# Generated by Django 5.2.6 on 2025-09-14 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_agent_ip_address_agent_registration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_service_id",
                    models.CharField(
                        help_text="The local, "
                        "non-unique ID of the service on the agent machine.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("schedule", models.CharField(blank=True, max_length=255)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OK", "OK"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UPDATE", "Update"),
                            ("FAILURE", "Failure"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_message", models.TextField(blank=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last status update.",
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("agent", "agent_service_id")},
            },
        ),
    ]
