# Generated by Django 5.2.6 on 2025-09-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="agent",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
