# Generated by Django 5.2.6 on 2025-09-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_agentregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentregistration",
            name="user",
        ),
    ]
