# Generated by Django 5.2.6 on 2025-09-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_agentregistration_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                help_text="A friendly name for the agent."
                " Can be auto-generated on registration.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("OK", "OK"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("UPDATE", "Update"),
                    ("FAILURE", "Failure"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
    ]
