# Generated by Django 5.2.6 on 2025-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_agent_name_alter_service_last_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="active_connections",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
