# Generated by Django 5.2.6 on 2025-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_agent_active_connections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="active_connections",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The current number of active connections to the agent.",
            ),
        ),
    ]
