# Generated by Django 5.2.6 on 2025-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_agent_active_connections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="active_connections",
        ),
        migrations.AddField(
            model_name="agent",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of the last update from the agent.",
                null=True,
            ),
        ),
    ]
