# Generated by Django 5.2.6 on 2025-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_agent_active_connections_agent_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last update from the agent.",
                null=True,
            ),
        ),
    ]
