# Generated by Django 5.2.6 on 2025-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_agent_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="current_channel_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The channel name of the current active WebSocket " "connection."
                ),
                max_length=255,
            ),
        ),
    ]
