# Generated by Django 5.2.9 on 2026-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_agent_current_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="current_channel_name",
        ),
        migrations.AlterField(
            model_name="agent",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the agent was disconnected.",
                null=True,
            ),
        ),
    ]
