# Generated by Django 6.0.1 on 2026-02-12 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_agent_current_channel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="grace_period",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Seconds to wait before marking agent as disconnected(0 for immediate, max 300).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
