# Generated by Django 6.0.1 on 2026-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_agent_grace_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="connection_id",
            field=models.UUIDField(
                blank=True,
                help_text="Unique ID for the current active WebSocket connection.",
                null=True,
            ),
        ),
    ]
