# Generated by Django 5.2.6 on 2025-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbbackup_admin", "0002_alter_backup_file_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backup",
            options={"ordering": ["-completed_at"]},
        ),
    ]
