# Generated by Django 4.2 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbbackup_admin", "0003_alter_backup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
