# Generated by Django 4.2 on 2025-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbbackup_admin", "0004_backup_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backup",
            options={"ordering": ["-backup_created_at"]},
        ),
        migrations.RenameField(
            model_name="backup",
            old_name="created_at",
            new_name="record_created_at",
        ),
        migrations.AddField(
            model_name="backup",
            name="backup_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
