# Generated by Django 4.2 on 2025-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbbackup_admin", "0005_alter_backup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="env",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
