# Generated by Django 5.2.6 on 2025-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbbackup_admin", "0006_backup_env"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backup",
            name="completed_at",
        ),
    ]
