# Generated by Django 5.2.6 on 2025-09-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("device_name", models.CharField(max_length=255)),
                (
                    "os_name",
                    models.CharField(
                        choices=[
                            ("Android", "Android"),
                            ("iOS", "iOS"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=50,
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "🟢 Active"), ("inactive", "🔴 Inactive")],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "token")},
            },
        ),
    ]
