# Generated by Django 5.2.6 on 2025-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
